### ISSUE TITLE
Server tests on packages not running

### ISSUE THREAD

**Issue by flippyhead** [DispatchMe/meteor-mocha-browser#1]
In https://github.com/flippyhead/jsdom-error I'm attempting to use `dispatch:mocha-phantomjs` for my CricleCI tests and `dispatch:mocha-browser` for local testing. Following [your suggestions](https://github.com/DispatchMe/meteor-mocha-phantomjs/issues/2#issuecomment-208604052) the setup works however none of the server tests are run.

My understanding is that by not using `practical meteor:mocha` the server tests _should_ be running. I was expecting to see the same tests in the server console and the browser since my tests should be running in both places.

Thank you

**Comment by aldeed** [comment]
Closing issues. Everyone please use the latest version of [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). If you run in watch mode without setting the `TEST_BROWSER_DRIVER` env variable, it is the same as this package.
