### ISSUE TITLE
Empty reporting div loaded when inactive

### ISSUE THREAD

**Issue by ramijarrar** [DispatchMe/meteor-mocha-browser#3]
I've noticed that this package is injecting the reporting element (div#mocha) into `<body>` regardless of whether it is active. This can overflow the layout on certain pages which can lead to some unreliability in test results (particularly when running the acceptance test driver).

![screen shot 2016-05-23 at 8 57 00 am](https://cloud.githubusercontent.com/assets/9661116/15457020/75047af8-20c4-11e6-9db8-286d413f0e1b.png)

**Comment by aldeed** [comment]
Closing issues. Everyone please use the latest version of [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). If you run in watch mode without setting the `TEST_BROWSER_DRIVER` env variable, it is the same as this package.
