### ISSUE TITLE
client tests hang

### ISSUE THREAD

**Issue by hexsprite** [DispatchMe/meteor-mocha-browser#4]
Server tests run fine. When I try to open the client test URL it just hangs (waiting for response).

Don't have a ton of time to create a repro but thought I'd open this in case anyone else knows something or has other details to share...

**Comment by aldeed** [comment]
Closing issues. Everyone please use the latest version of [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). If you run in watch mode without setting the `TEST_BROWSER_DRIVER` env variable, it is the same as this package.
