### ISSUE TITLE
No tests run on 1.3.3 with webpack

### ISSUE THREAD

**Issue by fgm** [DispatchMe/meteor-mocha-browser#5]
Hello. I can't seem to find how to use the package to run integration tests (meteor test without --full-app) on our application, which uses meteor:webpack. The package always reports `passes: 0 failures: 0 duration: 0s` on client, and `0 passing (1ms)`on server.

There is no such problem with unit tests or full-app tests.

**Comment by aldeed** [comment]
Closing issues. Everyone please use the latest version of [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). If you run in watch mode without setting the `TEST_BROWSER_DRIVER` env variable, it is the same as this package.
