### ISSUE TITLE
Percent Passed Incorrect (100% when tests fail)

### ISSUE THREAD

**Issue by merlinstardust** [DispatchMe/meteor-mocha-browser#6]
I have 14 tests, 13 are passing, 1 is failing. I would expect my percent passed to be 92.8% or so. Instead I get 100%.

How can I fix this?

**Comment by aldeed** [comment]
Closing issues. Everyone please use the latest version of [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). If you run in watch mode without setting the `TEST_BROWSER_DRIVER` env variable, it is the same as this package.
