### ISSUE TITLE
Dialogs and other top level divs obscure report

### ISSUE THREAD

**Issue by jeffryan** [DispatchMe/meteor-mocha-browser#7]
I notice that after running the unit tests that top level divs like dialogs and toaster messages stay visible over the top of the report div.

In comparing this to practicalmeteor:mocha I notice that the divs remain present there as well but they do a little css trick to hide them. the tag their report div with a special class name (mocha-wrapper) and then they hide all top level divs under the body that don't have that class like this:
`body > *:not(.mocha-wrapper) {
    display: none;
}`

It's a nice trick that ensures the report is visible.

You could do the same thing with the following css:
`body > *:not(#mocha) {
    display: none;
}`

**Comment by aldeed** [comment]
Closing issues. Everyone please use the latest version of [dispatch:mocha](https://github.com/DispatchMe/meteor-mocha). If you run in watch mode without setting the `TEST_BROWSER_DRIVER` env variable, it is the same as this package.
